language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - clang-3.7
      - cmake
      - cmake-data

compiler:
  - clang

install:
  - git clone https://github.com/google/googletest.git googletest
  - cd googletest/googletest
  - cmake . && cmake --build .
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$PWD/include
  - export LIBRARY_PATH=$LIBRARY_PATH:$PWD
  - cd -
  - cd googletest/googlemock
  - cmake . && cmake --build .
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$PWD/include
  - export LIBRARY_PATH=$LIBRARY_PATH:$PWD
  - cd -

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
