language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - clang-3.7
      - cmake
      - cmake-data
      - libgtest-dev

compiler:
  - clang

before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.7 /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
