language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq install clang-3.5
  - sudo apt-get install -y libgtest-dev cmake
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script:
  - mkdir build
  - cd build
  - cmake .. && make
